# Generated by Django 4.1.2 on 2022-11-29 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturates', models.FloatField()),
                ('sugar', models.FloatField()),
                ('salt', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fibre', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_calories', models.FloatField()),
                ('needed_fat', models.FloatField()),
                ('needed_saturates', models.FloatField()),
                ('needed_sugar', models.FloatField()),
                ('needed_protein', models.FloatField()),
                ('needed_carbs', models.FloatField()),
                ('needed_fibre', models.FloatField()),
                ('needed_salt', models.FloatField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('age', models.IntegerField(default=None)),
                ('gender', models.BooleanField(default=False)),
                ('weight_goal', models.FloatField()),
                ('weight_goal_time', models.DateField()),
                ('vegeterian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(to='recipes.food')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('food_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recipes.food')),
                ('instructions', models.TextField()),
                ('tags', models.CharField(max_length=254)),
                ('ingredients', models.ManyToManyField(related_name='+', to='recipes.food')),
            ],
            bases=('recipes.food',),
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recipes.profile')),
                ('intake', models.ManyToManyField(blank=True, to='recipes.food')),
                ('nutrition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.nutrition')),
            ],
        ),
    ]
