# Generated by Django 4.1.2 on 2022-10-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('dateOfIntake', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('nameOfIngredient', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('amountOfIngredient', models.FloatField()),
                ('intake', models.ManyToManyField(to='recipes.diary')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('second_name', models.CharField(max_length=100)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(default=False)),
                ('weight_goal', models.FloatField()),
                ('weight_goal_time', models.DateField()),
                ('vegeterian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('nameOfRecipe', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('instructions', models.TextField()),
                ('tags', models.CharField(max_length=254)),
                ('ingredients', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.user'),
        ),
        migrations.CreateModel(
            name='Macro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('fat', models.FloatField()),
                ('saturates', models.FloatField()),
                ('sugars', models.FloatField()),
                ('salt', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('fibre', models.FloatField()),
                ('diary', models.ManyToManyField(to='recipes.diary')),
                ('ingredient', models.ManyToManyField(to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_condition', models.CharField(max_length=100)),
                ('doesUserHave', models.BooleanField(default=False)),
                ('profile', models.ManyToManyField(to='recipes.profile')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='recipes.profile'),
        ),
    ]
