# Generated by Django 3.2.3 on 2022-12-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_profile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
