# Generated by Django 3.2.3 on 2022-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_food_diary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='diary',
            field=models.ManyToManyField(default=None, null=True, to='recipes.Diary'),
        ),
    ]
