# Generated by Django 3.2.3 on 2022-12-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221202_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
