# Generated by Django 3.2.3 on 2022-11-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_food_diary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='diary',
        ),
        migrations.AddField(
            model_name='diary',
            name='intake',
            field=models.ManyToManyField(to='recipes.Food'),
        ),
    ]
