# Generated by Django 3.2.3 on 2022-11-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221126_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='intake',
            field=models.ManyToManyField(blank=True, to='recipes.Food'),
        ),
    ]
